### ISSUE TITLE
Revise and automate docs with sphinx and host on readthedocs

### ISSUE THREAD

**Issue by lukpueh** [secure-systems-lab/securesystemslib#271]
**Description of issue or feature request**:
Revise docstrings of API functions regarding contents and format (use Google Style docstring as suggested in https://github.com/secure-systems-lab/code-style-guidelines/issues/20), akin to what in-toto did in https://github.com/in-toto/in-toto/pull/369.

Needs coordination with #270

**Current behavior**:
- No clear API
- Docstrings use custom secure systems lab format

**Expected behavior**:
- Clear API via #270 
- Use Google-style quasi standard docstring format (see [napoleon sphinx extension](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html#example-google))
- Revise doc contents (aim for conciseness)

**Comment by MVrachev** [comment]
Please note that when we update the docstrings of API functions we should update the
documentation regarding the `securesystemslib.keys.create_signature()` and the following comment
https://github.com/secure-systems-lab/securesystemslib/blob/a7d36681f32642fce10bc8aa051f394f8e6f0858/securesystemslib/keys.py#L709
because we are not actually supporting `ecdsa-sha2-nistp384`.
If you read `securesystemslib.ecdsa_keys.create_signature()`:
https://github.com/secure-systems-lab/securesystemslib/blob/a7d36681f32642fce10bc8aa051f394f8e6f0858/securesystemslib/ecdsa_keys.py#L173
you will see we support only support `ecdsa-sha2-nistp256`.
