### ISSUE TITLE
Add support for DSSE

### ISSUE THREAD

**Issue by adityasaky** [secure-systems-lab/securesystemslib#370]
**Description of issue or feature request**:

[Dead Simple Signing Envelope (DSSE)](https://github.com/secure-systems-lab/dsse) is the new signature wrapper recommended for use in in-toto (https://github.com/in-toto/ITE/blob/master/ITE/5/README.adoc) and TUF (pending https://github.com/theupdateframework/taps/pull/138). Naturally, it makes sense for its implementation to live in securesystemslib.

With ITE-5 up for acceptance (https://github.com/in-toto/ITE/issues/22), we are trying to define a transition period for in-toto during which the reference implementation supports generating and verifying metadata in both formats. This time period is dependent at least in part on the DSSE functionality being present in securesystemslib for in-toto to use. We can tentatively define a relative transition period, perhaps a year after in-toto starts supporting both wrappers.

**Current behavior**:

securesystemslib provides some crypto-specific primitives used by TUF and in-toto. Both projects maintain their own implementation of the current signature wrapper.

**Expected behavior**:

securesystemslib continues providing the functionality it currently does and adds DSSE support, allowing the python implementations of both TUF and in-toto to transition to the new wrapper.

cc @SantiagoTorres @joshuagl @mnm678 @trishankatdatadog

**Comment by adityasaky** [comment]
For reference, there's currently support for DSSE in in-toto-golang: https://github.com/in-toto/in-toto-golang/tree/master/pkg/ssl. The DSSE specification also includes an implementation we can likely borrow from here: https://github.com/secure-systems-lab/dsse/tree/master/implementation

**Comment by lukpueh** [comment]
Related: https://github.com/secure-systems-lab/securesystemslib/issues/272

**Comment by lukpueh** [comment]
A working DSSE implementation is available in https://github.com/secure-systems-lab/securesystemslib/compare/master...in-toto:securesystemslib:master courtesy of @PradyumnaKrishna! ❤️  (see [GSoC blog post](https://onpy.in/posts/gsoc-22/) for context). The implementation was tailored for in-toto (https://github.com/in-toto/in-toto/pull/503) but should work for python-tuf as well.

The result is a ~1,4K LOC diff, which I have reviewed in the course of multiple downstream PRs. Other maintainers should still take a look before we upstream. So I suggest to either:
- PR all at once and keep the nicely curated commit history, or
- PR module by module and make reviews more fun.

If we do the latter, I'm happy to coordinate the PRs and make sure that important information from the original commit history is preserved.

Since the decision depends mostly on how much we can ask from potential reviewers, I should voice their preference.

cc @jku, @joshuagl, @MVrachev, @adityasaky

----

**Diff overview** (ordered by degree of dependence from least to most, w/o tests)

- [util.py](https://github.com/in-toto/securesystemslib/blob/2a3d4a887d0389d8fde1bb500cc829d447b33e28/securesystemslib/util.py) -- DSSE-compliant b64enc and b64dec methods

- [exceptions.py](https://github.com/in-toto/securesystemslib/blob/2a3d4a887d0389d8fde1bb500cc829d447b33e28/securesystemslib/exceptions.py)  -- DSSE signature verification error and generic de/serialization errors

  TODO: Coordinate new signature verification error added here and in [#456](https://github.com/secure-systems-lab/securesystemslib/pull/456).

- [key.py](https://github.com/in-toto/securesystemslib/blob/2a3d4a887d0389d8fde1bb500cc829d447b33e28/securesystemslib/key.py) -- Abstract Key interface plus SSlibKey and GPGKey implementations

  TODO: Drop in favor of very similar `*Key` implementations from [#456](https://github.com/secure-systems-lab/securesystemslib/pull/456). GPGKey should be dropped altogether but may be upstreamed at a later point e.g. as BetterGPGKey (see [#456 discussion](https://github.com/secure-systems-lab/securesystemslib/pull/456#issuecomment-1315133573)).

- [serialization.py](https://github.com/in-toto/securesystemslib/blob/2a3d4a887d0389d8fde1bb500cc829d447b33e28/securesystemslib/serialization.py) --  Port of tuf.api.serialization

  *NOTE: The main difference is that the securesystemslib JSON deserializer only calls `json.loads` but does not instantiate a user-specific object (such as Metadata). The latter would need to happen in a subclass (e.g. [PayloadDeserializer](https://github.com/in-toto/in-toto/blob/158c9ba254ad72bd7690e7a2e06a9ed4f29bf615/in_toto/models/serialization.py#L31-L46), [AnyMetadataDeserializer](https://github.com/in-toto/in-toto/blob/158c9ba254ad72bd7690e7a2e06a9ed4f29bf615/in_toto/models/serialization.py#L49-L64), [EnvelopeJSONDeserializer](https://github.com/in-toto/securesystemslib/blob/2a3d4a887d0389d8fde1bb500cc829d447b33e28/securesystemslib/metadata.py#L17-L39))*

  TODO (optional): Assess whether this is useful for the tuf metadata api, which served as inspiration. Regardless, this should be in securesystemslib, because it is useful for in-toto and DSSE. 

- [metadata.py](https://github.com/in-toto/securesystemslib/blob/2a3d4a887d0389d8fde1bb500cc829d447b33e28/securesystemslib/metadata.py) -- DSSE envelope with methods to create and verify signatures, and to de/serialize envelope and payload
  TODO: 
    - Replace  `match_keyid` with simple keyid `==`-matching (see[ #456 discussion](https://github.com/secure-systems-lab/securesystemslib/pull/456#issuecomment-1315138451))
    - Don't case handle SIGNATURE_SCHEMA/GPG_SIGNATURE_SCHEMA (DSSE should use a GPGSigner that generates normal Signature objects)
    - Maybe find better names than `create_sig ` and `verify_sigs` (`sign` and `verify_signatures` are already taken, see https://github.com/in-toto/securesystemslib/commit/f418b3fcfd90b14b876693343b5155721077961e)

**Comment by adityasaky** [comment]
I feel bad about the commit history, but I think I'd prefer it to be module by module personally.

**Comment by lukpueh** [comment]
Now that #456 is merged and we are starting to get a good feel for it (#442, #472) we should take a stab at this here too.

I suggest to just start with a single draft PR after all. This should make fixing conflicts easier (see [TODOs in comment above](https://github.com/secure-systems-lab/securesystemslib/issues/370#issuecomment-1317414319)). And maybe the diff becomes small enough to review all at once. If not we can still split by modules.

@PradyumnaKrishna, are you still up for the task?

**Comment by PradyumnaKrishna** [comment]
Yes, I am up for it.
