### ISSUE TITLE
Unused variables and constants

### ISSUE THREAD

**Issue by trishankatdatadog** [secure-systems-lab/securesystemslib#432]
**Description of issue or feature request**:

There are unused variables and constants everywhere. We should add a linter to catch them.

**Comment by joshuagl** [comment]
+1, there are rather a lot of unused imports.

Our custom coding style prevented us adding an automated linter like black in the past and, frankly, likely prevented anyone from putting in the effort to use another less opinionated linter. We do have an old issue about linting at least new files https://github.com/secure-systems-lab/securesystemslib/issues/243 however, we didn't get much further than running mypy against new files.

**Comment by trishankatdatadog** [comment]
I think we should just move over to standard coding style enforced by common linters, TBH, not easy to follow and check for a custom style

**Comment by lukpueh** [comment]
FYI:
#439 formats everything with black and isort, and enables pylint and bandit.

To make review of #439 as easy as possible, I just disabled pylint for all lines that were flagged by adding `# pylint: disable=...` inline comments.

To fix this issue here, I suggest to
1. Merge [#439](https://github.com/secure-systems-lab/securesystemslib/pull/439)
2. Find relevant lines by `grep -ro '# pylint: disable=.*unused.*$' tests securesystemslib`
3. Fix & PR
