### ISSUE TITLE
Specify optional dependencies per feature

### ISSUE THREAD

**Issue by lukpueh** [secure-systems-lab/securesystemslib#482]
We use optional dependencies (aka. [extras](https://peps.python.org/pep-0508/#extras)) to allow a default installation with limited capabilities (e.g. verify ed25519 signatures using a pure Python implementation), which is useful for securesystemslib dependents (e.g. python-tuf), that need to be installable without any native dependencies (e.g. vendored into pip).

The full or a specific larger feature-set (e.g. signing) can be installed by specifying those extras like so:
```
pip install securesystemslib[crypto, asn1, pykcs11] # for hsm signing support
```
Except for hiding version constraints this is hardly more useful than telling user to install like so
```
pip install cryptography asn1crypto PyKCS11
```

**Current behavior**:

Specified per library:
https://github.com/secure-systems-lab/securesystemslib/blob/e2a08b123476ff05d1c3163eb6eeb3c705754952/pyproject.toml#L45-L51

**Expected behavior**:
- figure out what "features(s)" `cryptography`, `pynacl` should be mapped to (or leave those as they are)
- specify per feature, 
```python
[project.optional-dependencies]
[...]
gcpkms = ["google-cloud-kms"]
pq = ["PySPX==0.5.0"]
hsm = ["asn1crypto", "PyKCS11", "cryptography"]
```

**Caveat:**
Specifying them per feature is prone to redundancy. E.g. `cryptography` is needed for an hsm signing, but also for a traditional securesystemslib signing and gpg singing.

**Comment by jku** [comment]
I suppose the real "features" look roughly like this:

**feature**:  dependency
**ed25519 (sign)**: pynacl 
**ECDSA**: cryptography 
**RSA**: cryptography 
**SPHINCS**: PySPX
**GCP**:  google-cloud-kms, cryptography
**HSM**: asn1crypto, PyKCS11, cryptography

The first four are just scheme-support that forces a certain version: whether we name the feature by the scheme-family or the dependency itself is not very important I think? Maybe we just leave them as they are (so the feature name is the dependency name) so we don't annoy existing users?

Last two (and hopefully more future features) are more interesting and should be named by the feature: I guess the acronyms are good enough? I don't see any major issue with the redundancy

_Maybe_ GPG feature should also be defined -- it does depend on cryptography at least -- but I can see why that would be misleading as well... So maybe let's not tackle that issue here.
