### ISSUE TITLE
tests should not fail by default (PYKCS11LIB env var)

### ISSUE THREAD

**Issue by jku** [secure-systems-lab/securesystemslib#527]
Currently if you install securesystemslib and run the tests as instructed (`tox` or `tox -e py`), you  get:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'PYKCS11LIB'
```

This is wrong and likely really hard to figure out for a new developer
* CI should keep running with HSM tests enabled
* By default developer testing must not include HSM tests if the testing setup can't be made fool proof (AFAICT it can't)

**Comment by lukpueh** [comment]
Agreed. I think we can just remove the assertion responsible for the error:
https://github.com/secure-systems-lab/securesystemslib/blob/3a08f0f3a1975f5e58b062138f01e41957130531/tox.ini#L23

For context, I added the check so that we don't silently skip the tests on CI. But since we [actively set that environment variable in CI](https://github.com/secure-systems-lab/securesystemslib/blob/3a08f0f3a1975f5e58b062138f01e41957130531/.github/workflows/ci.yml#L56-L72), this is less likely to happen (as for e.g. gpg, where we use a similar assert).
