### ISSUE TITLE
SigstoreSigner: provide public key import for ambient credentials

### ISSUE THREAD

**Issue by lukpueh** [secure-systems-lab/securesystemslib#536]
e.g. `import_github_action()` could take repository, workflow and branch name to construct the identity string (issuer url is static):
https://github.com/secure-systems-lab/securesystemslib/blob/2acf318a9c49c0a5357e753917bd7ba5df51d1f2/.github/workflows/test-sigstore.yml#L35-L36

originally posted by @jku in #533

**Comment by jku** [comment]
bit more detail:

securesystemslib/signer/_sigstore-signer.py already has a convenience method to import a key via authenticating: this is useful for the interactive case but not for github actions case. For GitHub Actions you currently need to know how to build the identity and issuer strings: examples are
"https://github.com/jku/tuf-on-ci-sigstore-test/.github/workflows/online-sign.yml@refs/heads/main" and "https://token.actions.githubusercontent.com").
 
We can make this easier since for GitHub Actions the latter value is constant and the former is built of components that will be easier to understand if they are separated arguments... 

### github action import

    @classmethod
    def import_github_actions(
        cls, project: str, workflow_path: str, ref=None: Optional[str]
    ) -> Tuple[str, SigstoreKey]
 
 this would be called like `uri, key = SigstoreSigner.import_github_actions("jku/tuf-on-ci-sigstore-test", ".github/workflows/online-sign.yml")`: this would create a signer and key for the https://github.com/jku/tuf-on-ci-sigstore-test project main branch (where identity is "https://github.com/jku/tuf-on-ci-sigstore-test/.github/workflows/online-sign.yml@refs/heads/main" and issuer is "https://token.actions.githubusercontent.com")
